version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - kazkansouh

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - kazkansouh
    groups:
      org.junit.jupiter:
        patterns: ["org.junit.jupiter:*"]
    ignore:
      # ignore junit 6 as it does not support java 11
      - dependency-name: org.junit.jupiter:*
        update-types:
          - version-update:semver-major
